import { Product, QuizQuestion } from './types';

export const products: any[] = [
  {
    id: 1,
    name: "5Amino-1mq",
    unit: "50mg",
    stock: 10,
    price: 4050,
    cat: "Weight Loss",
    desc: "NNMT inhibitor designed for research regarding energy expenditure, cellular metabolism, and muscle tissue adaptation.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "5A1Q",
    popularity: 88
  },
  {
    id: 2,
    name: "AOD",
    unit: "5mg",
    stock: 3,
    price: 2925,
    cat: "Weight Loss",
    desc: "Anti-obesity drug fragment of human growth hormone studied for lipolytic activity and metabolic research.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "AOD",
    popularity: 74
  },
  {
    id: 3,
    name: "BPC-157",
    unit: "10mg",
    stock: 8,
    price: 2407.5,
    cat: "Peptides",
    desc: "Stable gastric pentadecapeptide researched extensively for tissue recovery, tendon healing, and gut barrier repair.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "BPC10",
    popularity: 95
  },
  {
    id: 4,
    name: "BPC157+TB500",
    unit: "10mg",
    stock: 1,
    price: 3240,
    cat: "Peptides",
    desc: "A synergistic blend of BPC-157 and Thymosin Beta-4 (TB-500) designed to study coordinated cellular recovery cascades.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "BPC+TB",
    popularity: 92
  },
  {
    id: 5,
    name: "Cagrilintide",
    unit: "5mg",
    stock: 1,
    price: 3645,
    cat: "Weight Loss",
    desc: "Amylin analogue studied for its interaction with GLP-1 receptors in regulation of appetite and fullness signals.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "CAGRI",
    popularity: 63
  },
  {
    id: 6,
    name: "CJC 1295 w/o DAC + IPA",
    unit: "10mg",
    stock: 2,
    price: 5512.5,
    cat: "Peptides",
    desc: "A combination GHRH (without Drug Affinity Complex) and Ipamorelin research compound for pulsatile growth factor stimulation.",
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=500&auto=format&fit=crop&q=80",
    abbr: "CJC+IPA",
    popularity: 79
  },
  {
    id: 7,
    name: "DSIP",
    unit: "5mg",
    stock: 2,
    price: 1935,
    cat: "Cognitive & Sleep",
    desc: "Delta sleep-inducing peptide researched for neuro-endocrine regulation, stress resilience, and deep recovery rhythms.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    abbr: "DSIP",
    popularity: 58
  },
  {
    id: 8,
    name: "Epitalon",
    unit: "50mg",
    stock: 2,
    price: 4387.5,
    cat: "Cognitive & Sleep",
    desc: "Synthetic tetrapeptide researched for biological telomerase activation, pineal gland regulation, and circadian alignment.",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=500&auto=format&fit=crop&q=80",
    abbr: "EPI50",
    popularity: 81
  },
  {
    id: 9,
    name: "Epitalon",
    unit: "10mg",
    stock: 2,
    price: 2070,
    cat: "Cognitive & Sleep",
    desc: "High-purity Epitalon tetrapeptide focused on study of molecular longevity, cellular renewal, and oxidative stress pathways.",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=500&auto=format&fit=crop&q=80",
    abbr: "EPI10",
    popularity: 72
  },
  {
    id: 10,
    name: "GHK-CU",
    unit: "100mg",
    stock: 8,
    price: 1912.5,
    cat: "Peptides",
    desc: "Copper tripeptide studied for gene expression modulation, wound repair, collagen synthesis, and topical tissue remodeling.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "GHK100",
    popularity: 90
  },
  {
    id: 11,
    name: "GHK-CU",
    unit: "50mg",
    stock: 5,
    price: 1687.5,
    cat: "Peptides",
    desc: "An optimal dosage of Copper-binding tripeptide tested in research paradigms for antioxidant defenses and fibroblast growth.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "GHK50",
    popularity: 85
  },
  {
    id: 12,
    name: "GHK-CU + KPV",
    unit: "60mg",
    stock: 2,
    price: 3735,
    cat: "Peptides",
    desc: "A novel synergized formula of GHK-Cu and anti-inflammatory tripeptide KPV to study dual pathways of tissue recovery.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "GHK+KPV",
    popularity: 82
  },
  {
    id: 13,
    name: "GHK-CU Topical",
    unit: "1G",
    stock: 6,
    price: 2025,
    cat: "Peptides",
    desc: "Specially prepared 1000mg GHK-Cu laboratory standard suited for non-invasive topical delivery and epidermal studies.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "GHK-TOP",
    popularity: 80
  },
  {
    id: 14,
    name: "Glow",
    unit: "70mg",
    stock: 1,
    price: 5400,
    cat: "Peptides",
    desc: "Premium cellular wellness and tissue-structural complex designed for specialized longevity and antioxidant research.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "GLOW",
    popularity: 71
  },
  {
    id: 15,
    name: "Glutathione Subq",
    unit: "1500mg",
    stock: 20,
    price: 2587.5,
    cat: "Peptides",
    desc: "High-concentration core cellular antioxidant studied for cellular detoxification, heavy metal binding, and redox maintenance.",
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=500&auto=format&fit=crop&q=80",
    abbr: "GLUT",
    popularity: 94
  },
  {
    id: 16,
    name: "Ipamorelin",
    unit: "10mg",
    stock: 2,
    price: 2587.5,
    cat: "Peptides",
    desc: "Selective GH secretagogue acting via ghrelin receptor pathway without affecting cortisol or prolactin secretion.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    abbr: "IPA10",
    popularity: 77
  },
  {
    id: 17,
    name: "Kisspeptin",
    unit: "5mg",
    stock: 1,
    price: 2362.5,
    cat: "Peptides",
    desc: "Biological decapeptide playing a vital upstream regulatory role in GnRH release and endocrine axis pathways.",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=500&auto=format&fit=crop&q=80",
    abbr: "KISS",
    popularity: 61
  },
  {
    id: 18,
    name: "KPV",
    unit: "10mg",
    stock: 9,
    price: 2475,
    cat: "Peptides",
    desc: "MC1R-active anti-inflammatory peptide evaluated in mucosal barrier preservation, gut microbiome wellness, and cytokine research.",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=500&auto=format&fit=crop&q=80",
    abbr: "KPV10",
    popularity: 87
  },
  {
    id: 19,
    name: "KPV",
    unit: "5mg",
    stock: 8,
    price: 2025,
    cat: "Peptides",
    desc: "Standard research vial of peptide KPV to investigate cellular immunomodulatory and mucosal protection dynamics.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "KPV5",
    popularity: 76
  },
  {
    id: 20,
    name: "LL37",
    unit: "5mg",
    stock: 1,
    price: 2700,
    cat: "Peptides",
    desc: "Only human cathelicidin-derived antimicrobial peptide studied for cellular defense, cytokine response, and angiogenesis.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "LL37",
    popularity: 65
  },
  {
    id: 21,
    name: "MOTs-C",
    unit: "10mg",
    stock: 8,
    price: 2362.5,
    cat: "Weight Loss",
    desc: "Mitochondrial-derived peptide researched for insulin sensitivity modulation, physical stamina optimization, and energy homeostasis.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "MOTS10",
    popularity: 89
  },
  {
    id: 22,
    name: "MOTs-C",
    unit: "40mg",
    stock: 5,
    price: 5625,
    cat: "Weight Loss",
    desc: "High-dose mitochondrial peptide standard focused on study of metabolic acceleration and biological cellular senescence pathways.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "MOTS40",
    popularity: 84
  },
  {
    id: 23,
    name: "NAD+",
    unit: "500mg",
    stock: 8,
    price: 2700,
    cat: "Cognitive & Sleep",
    desc: "Premium cellular coenzyme (Nicotinamide Adenine Dinucleotide) essential for ATP synthesis, DNA repair, and sirtuin cofactor studies.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "NAD+",
    popularity: 96
  },
  {
    id: 24,
    name: "Oxytocin",
    unit: "2mg",
    stock: 2,
    price: 1800,
    cat: "Cognitive & Sleep",
    desc: "Neuropeptide model utilized for investigations in social bonding mechanisms, neural trust circuitry, and stress responses.",
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=500&auto=format&fit=crop&q=80",
    abbr: "OXY",
    popularity: 69
  },
  {
    id: 25,
    name: "PT-141",
    unit: "10mg",
    stock: 2,
    price: 2407.5,
    cat: "Peptides",
    desc: "Melanocortin receptor agonist (Bremelanotide) studied for neurochemical arousal and energetic neural pathway stimulation.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    abbr: "PT141",
    popularity: 78
  },
  {
    id: 26,
    name: "Retatrutide",
    unit: "10mg",
    stock: 10,
    price: 3352.5,
    cat: "Weight Loss",
    desc: "Ultra-modern triple hormone agonist (GIP, GLP-1, and GCG receptors) evaluated for maximal energy balance and metabolic research.",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=500&auto=format&fit=crop&q=80",
    abbr: "RETA10",
    popularity: 99
  },
  {
    id: 27,
    name: "Retatrutide",
    unit: "30mg",
    stock: 11,
    price: 5625,
    cat: "Weight Loss",
    desc: "Maximal strength triple receptor targeting standard evaluated for major endocrine metabolic adjustments.",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=500&auto=format&fit=crop&q=80",
    abbr: "RETA30",
    popularity: 94
  },
  {
    id: 28,
    name: "Retatrutide",
    unit: "20mg",
    stock: 14,
    price: 4612.5,
    cat: "Weight Loss",
    desc: "Intermediate core Retatrutide standard focused on metabolic optimization and lipolysis pathway regulation studies.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "RETA20",
    popularity: 91
  },
  {
    id: 29,
    name: "Retatrutide",
    unit: "5mg",
    stock: 8,
    price: 2587.5,
    cat: "Weight Loss",
    desc: "Beginning titration research standard of Triple Agonist Retatrutide for preliminary receptor saturation research.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "RETA5",
    popularity: 88
  },
  {
    id: 30,
    name: "Retatrutide",
    unit: "15mg",
    stock: 1,
    price: 4027.5,
    cat: "Weight Loss",
    desc: "Custom balanced dosage of RETA designed for refined pharmacological assays and kinetic evaluation studies.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "RETA15",
    popularity: 80
  },
  {
    id: 31,
    name: "Semax",
    unit: "5mg",
    stock: 2,
    price: 1687.5,
    cat: "Cognitive & Sleep",
    desc: "Neurogenic heptapeptide researched for BDNF elevation, memory processing, cognitive retention, and focus assays.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "SEMAX",
    popularity: 83
  },
  {
    id: 32,
    name: "SLU-PP-322",
    unit: "5mg",
    stock: 1,
    price: 4050,
    cat: "Weight Loss",
    desc: "Estrogen-related receptor (ERR) agonist studied in research models for active exercise-mimetic metabolic acceleration.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "SLU322",
    popularity: 62
  },
  {
    id: 33,
    name: "SNAP 8",
    unit: "10mg",
    stock: 3,
    price: 2002.5,
    cat: "Peptides",
    desc: "Octapeptide studied for its ability to block neurotransmitter release at neuromuscular junctions, limiting muscle contraction signals.",
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=500&auto=format&fit=crop&q=80",
    abbr: "SNAP8",
    popularity: 70
  },
  {
    id: 34,
    name: "Tesamorelin",
    unit: "10mg",
    stock: 1,
    price: 5287.5,
    cat: "Peptides",
    desc: "GHRH analogue researched for core lipid regulation, deep metabolic restructuring, and pulsatile growth factor enhancement.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80",
    abbr: "TESA10",
    popularity: 75
  },
  {
    id: 35,
    name: "Tesamorelin",
    unit: "5mg",
    stock: 1,
    price: 3262.5,
    cat: "Peptides",
    desc: "Specialized low-dose growth hormone secretagogue analogue tailored for precise micro-dose research protocols.",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=500&auto=format&fit=crop&q=80",
    abbr: "TESA5",
    popularity: 68
  },
  {
    id: 36,
    name: "Tirzepatide",
    unit: "10mg",
    stock: 7,
    price: 2250,
    cat: "Weight Loss",
    desc: "Dual GIP and GLP-1 receptor agonist studied for visceral adipose dissolution, pancreatic signaling, and weight homeostasis.",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ10",
    popularity: 98
  },
  {
    id: 37,
    name: "Tirzepatide",
    unit: "20mg",
    stock: 8,
    price: 3150,
    cat: "Weight Loss",
    desc: "Robust biological GIP/GLP-1 agonist formulation designed to review advanced endocrine responses.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ20",
    popularity: 93
  },
  {
    id: 38,
    name: "Tirzepatide",
    unit: "30mg",
    stock: 7,
    price: 3667.5,
    cat: "Weight Loss",
    desc: "Advanced biological research standard of dual peptide Tirzepatide to examine maximal receptor synergy.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ30",
    popularity: 90
  },
  {
    id: 39,
    name: "Tirzepatide",
    unit: "15mg",
    stock: 7,
    price: 2857.5,
    cat: "Weight Loss",
    desc: "Optimally calibrated Tirzepatide standard focused on metabolic and blood glucose level homeostasis evaluation.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ15",
    popularity: 87
  },
  {
    id: 40,
    name: "Tirzepatide",
    unit: "50mg",
    stock: 1,
    price: 5017.5,
    cat: "Weight Loss",
    desc: "High-yield dual GIP/GLP-1 model focused on massive sample scale testing and biochemical research.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ50",
    popularity: 81
  },
  {
    id: 41,
    name: "Tirzepatide",
    unit: "60mg",
    stock: 2,
    price: 5917.5,
    cat: "Weight Loss",
    desc: "Maximum capacity sample vial of GIP/GLP-1 analogue suited for extensive parallel cohort assays.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ60",
    popularity: 85
  },
  {
    id: 42,
    name: "Tirzepatide",
    unit: "40mg",
    stock: 2,
    price: 4320,
    cat: "Weight Loss",
    desc: "Extended metabolic standard formulation for long-term chronic studies in test subjects.",
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=500&auto=format&fit=crop&q=80",
    abbr: "TIRZ40",
    popularity: 83
  },
  {
    id: 43,
    name: "Bacteriostatic Water",
    unit: "10ml",
    stock: 100,
    price: 180,
    cat: "Supplies",
    desc: "Premium Bacteriostatic Water containing 0.9% Benzyl Alcohol, crucial for the preservation and reconstitution of research peptides.",
    image: "https://images.unsplash.com/photo-1620756206888-c30177e6f142?w=500&auto=format&fit=crop&q=80",
    abbr: "BAC10",
    popularity: 100
  },
  {
    id: 44,
    name: "Peppie Pen V1 (Candy Pink)",
    unit: "1 Unit",
    stock: 15,
    price: 1450,
    cat: "Pens",
    desc: "Vibrant and ergonomic premium research dose delivery pen, calibrated for micro-dose laboratory liquid handling.",
    image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
    abbr: "PEN-V1-PNK",
    popularity: 92
  },
  {
    id: 45,
    name: "Peppie Pen V1 (Ocean Blue)",
    unit: "1 Unit",
    stock: 12,
    price: 1450,
    cat: "Pens",
    desc: "Professional ocean-blue finish research delivery pen, designed with an adjustable micro-dial for volume precision.",
    image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
    abbr: "PEN-V1-BLU",
    popularity: 88
  },
  {
    id: 46,
    name: "Peppie Pen V4 (Midnight Black)",
    unit: "1 Unit",
    stock: 8,
    price: 1850,
    cat: "Pens",
    desc: "High-grade carbon alloy casing research pen featuring heavy-duty gear dials for high-viscosity reagents control.",
    image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
    abbr: "PEN-V4-BLK",
    popularity: 95
  },
  {
    id: 47,
    name: "Insulin Syringes (30G, 1ml)",
    unit: "100 Units",
    stock: 50,
    price: 850,
    cat: "Supplies",
    desc: "Ultra-fine medical grade syringes designed for smooth liquid measurement and laboratory reconstitution transfer.",
    image: "https://images.unsplash.com/photo-1615461066841-6116ecdacdca?w=500&auto=format&fit=crop&q=80",
    abbr: "SYR30G",
    popularity: 91
  },
  {
    id: 48,
    name: "Pen Needles (32G, 4mm)",
    unit: "100 Units",
    stock: 40,
    price: 650,
    cat: "Supplies",
    desc: "Micro pen needles compatible with all standard research delivery pens, including Peppie Pen models.",
    image: "https://images.unsplash.com/photo-1607619056574-7b8f30413736?w=500&auto=format&fit=crop&q=80",
    abbr: "NDL32G",
    popularity: 87
  },
  {
    id: 49,
    name: "Syringe Filters (0.22µm)",
    unit: "10 Units",
    stock: 25,
    price: 450,
    cat: "Supplies",
    desc: "PES sterile-filtered syringe filters designed to sterilize research solutions during laboratory preparation.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    abbr: "FLTR22",
    popularity: 80
  },
  {
    id: 50,
    name: "Premium Reconstitution Kit",
    unit: "1 Kit",
    stock: 30,
    price: 1200,
    cat: "Supplies",
    desc: "Complete laboratory starter kit containing 2x Bacteriostatic Water, 30x Insulin Syringes, and 30x Alcohol Prep Pads.",
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80",
    abbr: "RECON-KIT",
    popularity: 97
  }
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: "What is your primary scientific research pathway?",
    options: [
      { label: "Cellular Repair & Healing Mechanisms", value: "Peptides", icon: "activity" },
      { label: "Lipolysis, Appetite Satiety & GLP-1 Dynamics", value: "Weight Loss", icon: "scale" },
      { label: "Circadian rhythms, Pineal pathways & Telomerase", value: "Cognitive & Sleep", icon: "brain" },
      { label: "Reconstitution and Basic Lab Solutes", value: "Lab Essentials", icon: "beaker" }
    ]
  },
  {
    id: 2,
    question: "Which peptide formulation strength does your protocol require?",
    options: [
      { label: "Highly Concentrated Vials (Max Efficiency)", value: "strong", icon: "zap" },
      { label: "Standard Assay Ratios (Titration Standard)", value: "standard", icon: "target" }
    ]
  }
];
